#как application.properties
some:
  text:
    str: 'eee'

server:
  port: '417'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clones_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true